#!/usr/bin/env bash
# Configuring web-02 to be identical to web-01
sudo apt-get -y update
sudo apt-get -y install nginx

# Adding content to the web pages
echo 'Heloo World!' | sudo tee /var/www/html/index.nginx-debian.html
echo 'Ceci n\'est pas une page' | sudo tee /var/www/html/custom_404.html

# Configuring redirection
sudo sed -i '/^\s*server_name.*;/a \ \ \ \ rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Custom error page
sudo sed -i '/^\s*location \/ {/i \ \ \ \ error_page 404 /custom_404.html;' /etc/nginx/sites-available/default

# Configuring response header
sudo sed -i '/^\s*location \/ {/i \ \ \ \ add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restarting the server to apply changes
sudo service nginx restart

