#!/usr/bin/bash
# Does the following:
# Create a file /var/run/myscript.pid containing the script PID.
# Displays "To infinity and beyond" indefinitely
# Displays "I hate the kill command" upon recieving a SIGTERM
# Display "Y U no love me?!" upon recieving a SIGINT
# deletes the file /var/run/myscript.pid and terminates upon
#+ recieving a SIGQUIT or SIGTERM.

terminator() {
   rm /var/run/myscript.pid
   exit
}

echo "$$ > /var/run/myscript.pid

while true
do
   echo "To infinity and beyond"
   trap 'echo "Y U no love me?!"' SIGINT
   trap 'echo "I hate the kill command" && terminator'
SIGTERM
   trap 'terminator' SIGQUIT
done
