#!/usr/bin/env bash
# Lets install ufw firewall and setup a few rules on web-01

sudo apt install -y ufw
sudo ufw default allow outgoing
sudo ufw default deny incomming
sudo ufw allow 22 
sudo ufw allow 443
sudo ufw allow 80
echo "y" | sudo ufw enable
